# 备份 Matrix 的任务
- name: Backup Matrix   # 这个任务的名称
  tags:                 # 这个任务有哪些标签，方便指定执行
    - backup_matrix
  hosts: MatrixServer   # 这个任务的机器是哪台
  vars:                 # 这个任务的变量
    large_directory: /matrix/synapse/storage/media-store
    temporary_store_directory: /tmp/matrix_bak/   # 暂时必须带 /
    specify_directory_in_remote: MatrixServer
  roles:                # 按顺序，让角色们行动
    - matrix_backup
  tasks:                # 另外的边角任务，删除机器上 mc 的服务端的配置信息，保证安全
    - name: delete mc config
      shell: "mc alias rm {{ minio_alias }}"

# 备份 技焉洲 WordPress 的任务
- name: Backup Technique
  tags: 
    - backup_technique
  hosts: TechniqueServer
  vars:
    temporary_store_directory: /tmp/technique_bak   # 不能带 /
    specify_directory_in_remote: TechniqueServer
    systemdservice_name_list: [lsws]
    mysql_user: wp_user
    mysql_password: password
    mysql_dbname: wp_db
    wordpress_directory: /usr/local/lsws/wordpress
    large_directory: "{{ wordpress_directory }}"
  roles:
    - wordpress_backup
  tasks:
    - name: delete mc config
      shell: "mc alias rm {{ minio_alias }}"

- name: Backup Imagebed
  tags: 
    - backup_imagebed
  hosts: TechniqueServer
  vars:
    backup_file_name: imagebed_bak
    temporary_store_directory: /tmp/imagebed_bak   # 不能带 /
    backup_directory: /mnt/minio
    excluded_directory: --exclude=/mnt/minio/upload # 目前只会这样，以后完善
    specify_directory_in_remote: ImagebedServer
    systemdservice_name_list: [minio]
    large_directory: "{{ backup_directory }}"   # 如果存在，则比较硬盘剩余空间与该目录大小
    in_encryption: true
  roles:
    - imgbed_backup
